name: Core Tests

on:
  push:
    branches: [main]
    paths: ['core/**', '.github/workflows/core-test.yml']
  pull_request:
    paths: ['core/**', '.github/workflows/core-test.yml']

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MOONBIT_VERSION: 0.9.0+9f1423bcb
    defaults:
      run:
        working-directory: core
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: ./.github/actions/setup-moonbit
        with:
          version: ${{ env.MOONBIT_VERSION }}
      - run: moon update
      - run: moon fmt --check
      - run: moon test --deny-warn
      - run: moon test --target native --deny-warn
      - run: moon build --target wasm-gc
      - run: moon build --target js
      - name: Check generated interface is up to date
        run: moon info && git diff --ignore-blank-lines --exit-code
