name: Core Tests

on:
  push:
    branches: [main]
    paths: ['core/**']
  pull_request:
    paths: ['core/**']

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: hustcer/setup-moonbit@e9b0a3082767ae669bf7588992ae3ba9eac09baa
      - run: moon fmt --check
      - run: moon test
      - run: moon build --target wasm-gc
      - run: moon build --target js
      - name: Check generated interface is up to date
        run: moon info && git diff --exit-code
