name: tagpr

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - uses: Songmu/tagpr@9bbb945b2fb025126186661e27d55485e3fc6df6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
